Repository deydoux/42cursus-ft_irc, pull requests merged in 2025-03, with the labels that each got.

#27 Fix MODE compilation errors
  src/class/Channel.cpp
  src/class/Command.cpp
Labels: fix

#32 NAMES Command + a few fixes
  include/class/Channel.hpp
  include/class/Client.hpp
  include/class/Command.hpp
  include/class/Server.hpp
  include/reply_code.hpp
  src/class/Channel.cpp
  src/class/Client.cpp
  src/class/Command.cpp
  src/class/Server.cpp
Labels: enhancement

#35 Hk option
  hk.templates
  include/class/Command.hpp
  include/reply_code.hpp
  src/class/Command.cpp
Labels: enhancement

#39 Part command
  include/class/Client.hpp
  include/class/Command.hpp
  src/class/Client.cpp
  src/class/Command.cpp
Labels: enhancement

#34 Implement bot
  .github/workflows/cpp.yml
  bot/.gitignore
  bot/Makefile
  bot/include/class/Curl.hpp
  bot/include/class/JSON.hpp
  bot/include/class/JSON.tpp
  bot/include/class/Ollama.hpp
  bot/src/class/Curl.cpp
  bot/src/class/JSON.cpp
  bot/src/class/Ollama.cpp
  bot/src/main.cpp
Labels: enhancement, help wanted

#40 Channel name fix
  include/class/Channel.hpp
  src/class/Channel.cpp
  src/class/Client.cpp
  src/class/Command.cpp
  src/class/Server.cpp
Labels: help wanted, fix

#42 Split commands into separated files
  Makefile
  include/class/Command.hpp
  include/reply_code.hpp
  src/class/Client.cpp
  src/class/Command.cpp
  src/class/Command/hk.cpp
  src/class/Command/invite.cpp
  src/class/Command/join.cpp
  src/class/Command/kick.cpp
  src/class/Command/mode.cpp
  src/class/Command/motd.cpp
  src/class/Command/names.cpp
  src/class/Command/nick.cpp
  src/class/Command/part.cpp
  src/class/Command/pass.cpp
  src/class/Command/ping.cpp
  src/class/Command/privmsg.cpp
  src/class/Command/quit.cpp
  src/class/Command/topic.cpp
  src/class/Command/user.cpp
  src/class/Command/who.cpp
Labels: enhancement

#44 Complete some TODOs
  include/class/Client.hpp
  src/class/Client.cpp
  src/class/Command/hk.cpp
  src/class/Command/invite.cpp
  src/class/Command/join.cpp
  src/class/Command/kick.cpp
  src/class/Command/mode.cpp
  src/class/Command/motd.cpp
  src/class/Command/names.cpp
  src/class/Command/nick.cpp
  src/class/Command/part.cpp
  src/class/Command/pass.cpp
  src/class/Command/ping.cpp
  src/class/Command/privmsg.cpp
  src/class/Command/quit.cpp
  src/class/Command/topic.cpp
  src/class/Command/user.cpp
  src/class/Command/who.cpp
Labels: enhancement

#43 ADD: '/join 0 ' command added
  include/class/Client.hpp
  src/class/Client.cpp
  src/class/Command/join.cpp
  src/class/Command/part.cpp
  src/class/Command/who.cpp
Labels: enhancement

#46 Irc client
  bot/Makefile
  bot/include/class/IRC.hpp
  bot/include/class/TriviaGame.hpp
  bot/include/lib.hpp
  bot/include/text_formatting.hpp
  bot/src/class/IRC.cpp
  bot/src/class/TriviaGame.cpp
  bot/src/lib/text_formatting.cpp
  bot/src/lib/trivia_phrases.cpp
Labels: enhancement

#47 Fetch trivia
  bot/Makefile
  bot/include/class/JSON.hpp
  bot/include/class/JSON.tpp
  bot/include/class/TriviaGame.hpp
  bot/include/lib.hpp
  bot/src/class/JSON.cpp
  bot/src/class/TriviaGame.cpp
  bot/src/lib/html_decode.cpp
Labels: enhancement

#48 Add early return for empty command arguments in Command::execute
  src/class/Command.cpp
Labels: fix

#50 Fix Client::is_channel_operator (oops, sorry)
  src/class/Channel.cpp
  src/class/Client.cpp
Labels: fix

#51 Fixed Trivia
  bot/Makefile
  bot/include/class/IRC.hpp
  bot/include/class/TriviaGame.hpp
  bot/include/lib.hpp
  bot/src/class/IRC.cpp
  bot/src/class/TriviaGame.cpp
  bot/src/lib/ft_strerror.cpp
  bot/src/lib/trivia_phrases.cpp
  bot/src/main.cpp
Labels: fix

#52 Bot Command Handlers: wrong number of arguments checker
  bot/include/class/IRC.hpp
  bot/src/class/IRC.cpp
Labels: fix

#54 Fix choices could be C or D for True/False question
  bot/src/class/TriviaGame.cpp
Labels: fix

#55 Add Ollama
  bot/include/class/IRC.hpp
  bot/include/class/Ollama.hpp
  bot/include/text_formatting.hpp
  bot/src/class/IRC.cpp
  bot/src/class/Ollama.cpp
  src/class/Client.cpp
Labels: enhancement

#56 The Refactor
  Makefile
  include/class/Channel.hpp
  include/class/Client.hpp
  include/class/Command.hpp
  include/class/Server.hpp
  include/lib.hpp
  src/class/Channel.cpp
  src/class/Client.cpp
  src/class/Command.cpp
  src/class/Command/join.cpp
  src/class/Command/kick.cpp
  src/class/Command/mode.cpp
  src/class/Command/names.cpp
  src/class/Command/part.cpp
  src/class/Command/privmsg.cpp
  src/class/Command/topic.cpp
  src/class/Command/who.cpp
  src/class/Server.cpp
  src/lib/match_mask.cpp
  src/lib/split.cpp
  src/lib/unix_timestamp.cpp
Labels: enhancement

#57 Made Ollama server uri unstatic
  bot/include/class/IRC.hpp
  bot/include/class/Ollama.hpp
  bot/src/class/IRC.cpp
  bot/src/class/Ollama.cpp
Labels: enhancement

#60 Add README
  README.md
Labels: enhancement

#62 Add bonus target to Makefile for building bot
  Makefile
Labels: enhancement

#63 Improve client disconnection handling by removing empty channels and deleting them
  src/class/Server.cpp
Labels: fix

#66 Handle exceptions during client disconnection to prevent crashes
  src/class/Client.cpp
Labels: fix
