Repository deydoux/42cursus-ft_irc, pull requests merged in 2025-02, with the labels that each got.

#6 Implement MOTD
  include/class/Client.hpp
  include/class/Command.hpp
  include/class/Server.hpp
  include/reply_code.hpp
  kittirc.motd
  src/class/Client.cpp
  src/class/Command.cpp
  src/class/Server.cpp
Labels: enhancement

#8 Fix channel verbose
  include/class/Channel.hpp
  src/class/Command.cpp
Labels: bug

#16 Kick command
  include/class/Channel.hpp
  include/class/Client.hpp
  include/class/Command.hpp
  include/reply_code.hpp
  src/class/Channel.cpp
  src/class/Client.cpp
  src/class/Command.cpp
  src/class/Server.cpp
Labels: enhancement

#17 Quit command
  include/class/Channel.hpp
  include/class/Client.hpp
  src/class/Channel.cpp
  src/class/Client.cpp
  src/class/Command.cpp
  src/class/Server.cpp
Labels: fix

#18 Fix JOIN Command
  include/class/Client.hpp
  include/class/Server.hpp
  src/class/Channel.cpp
  src/class/Client.cpp
  src/class/Command.cpp
  src/class/Server.cpp
Labels: fix
